spring.application.name=VOICENOX

spring.datasource.url=jdbc:mysql://localhost:3306/voicenox
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=1999

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

deepgram.api.key=${DEEPGRAM_API_KEY}
